export const AUTH_ERROR_CODES = {
    TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
    TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
    TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
    USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
    ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
    SERVICE_UNAVAILABLE: 'AUTH_SERVICE_UNAVAILABLE',
    FORBIDDEN: 'AUTH_FORBIDDEN',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    EMAIL_DELIVERY_FAILED: 'EMAIL_DELIVERY_FAILED',
    GOOGLE_LINK_REQUIRED: 'GOOGLE_LINK_REQUIRED',
    GOOGLE_IDENTITY_CONFLICT: 'GOOGLE_IDENTITY_CONFLICT',
    PASSWORD_SETUP_REQUIRED: 'PASSWORD_SETUP_REQUIRED',
} as const

export type AuthErrorCode = typeof AUTH_ERROR_CODES[keyof typeof AUTH_ERROR_CODES]

export function authError(error: string, code: AuthErrorCode) {
    return { error, code }
}
